modLoader="javafml"
loaderVersion="[46,)"

license="See the LICENSE file included in the source code of this mod"

[[mods]]
  modId="ocreloaded"
  version="${version}"
  displayName="OpenComputers Reloaded"
  displayURL="https://oc.cil.li/"
  logoFile="assets/ocreloaded/textures/gui/logo.png"
  credits="Based on the original OpenComputers mod, which was inspired by a few mods, most notably ComputerCraft."
  authors="EveryOS, 6TELOIV. Resources are from authors of original OpenComputers (Sangar, payonel, Vexatos and others)"
  description="Bring programmable computers to Minecraft! This mod is a complete rewrite of OpenComputers, but with extra goodies."

[[dependencies.ocreloaded]]
  modId="forge"
  mandatory=true
  versionRange="[46,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.ocreloaded]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20,]"
  ordering="NONE"
  side="BOTH"